config/routes.rb
Rails.application.routes.draw do
  get 'words/index'
  root 'static_pages#home'
  get '/signup',to:'users#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/login', to:'sessions#new'
  delete '/logout',to:'sessions#destroy'
  resources :users do
    member do
      get 'following', 'followers'
    end
  end
  resources :sessions
  resources :relationships,only:[:create,:destroy]
  namespace :admin do
    resources :static_pages do
      member do
        get 'admin_page'
      end
    end
    resources :users
    resources :categories do
      resources :words
    end
  end
  resources :categories
  get '/learned',to:'categories#learned'
  get '/not_learned',to:'categories#not_learned'
  resources :lessons do
    resources :answers
  end
  resources :words,only:[:index]
end

app/models/word.rb
class Word < ApplicationRecord
  belongs_to :category
  has_many :choices, dependent: :destroy
  accepts_nested_attributes_for :choices
  
  validates :content,presence: true,length:{maximum: 25}
  validate :has_one_correct

  def correct_answer
    choices.find_by(is_correct: true)    
  # このメソッドは@wordモデルの中にあるので、使いたい時は@word = ~~と指定してあから
  # @word.correct_answer.contentで使用できる。
  end

  private
    def has_one_correct
      unless choices.collect { |choice| choice.is_correct? }.count(true) ==1
        errors.add(:choices,"shoudle have one correct answer")
      end
    end
end

app/controllers/admin/words_controller.rb
class Admin::WordsController < ApplicationController
  def new
    @category = Category.find(params[:category_id])
    @word = @category.words.new
    3.times { @word.choices.new }
                                                          # 3回@wordのchoiceを繰り返します
  end

  def create
    @category = Category.find(params[:category_id])
    @word = @category.words.new(words_params)
    if @word.save
      redirect_to admin_category_words_url(@category)
    else
      render "new"
    end
  end
  
  def edit
    @category = Category.find(params[:category_id])
    @word = Word.find(params[:id])
  end

  def update
    @category = Category.find(params[:category_id])
    @word = Word.find(params[:id])
      if @word.update(words_params)
        redirect_to admin_category_words_url(@category)
      else
        render "edit"
      end
  end

  def destroy
    @category = Category.find(params[:category_id])
    @word = Word.find(params[:id])
    @word.destroy
    redirect_to admin_category_words_url(@category)
  end

  def index
    @category = Category.find(params[:category_id])
    @words = @category.words.paginate(page: params[:page], per_page: 5)
    
                                                          # @category = Category.find(params[:category_id])
                                                          # @words = @category.words
  end

  def show
    
  end

  private
  def words_params
    params.require(:word).permit(:content, choices_attributes:[:id, :content, :is_correct])
  end

end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  def index
    if params[:category]
      @category = Category.find(params[:category])
      @answers = @category.answers
      @words = @answers.paginate(page: params[:page], per_page: 6)
    else
      @answers = current_user.answers
      @words = @answers.paginate(page: params[:page], per_page: 6)
    end
    @categories = current_user.categories.left_outer_joins(:lessons).where.not(lessons:{result: nil})
  end
end

app/helpers/admin/words_helper.rb
module Admin::WordsHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/admin/words/_form.html.erb
<%= form_for([:admin, @category, @word]) do |f| %>

    <%= render "shared/error_message", object:f.object %>
    <%# エラーメッセージ %>
    
    <div class="text-left">
        <div class="form-group">
            <%= f.label :title %><br>
            <%= f.text_field :content,class:"form-control"%>
        </div>

        <%# お手本 %>

        <%# ここからthis is answer %>
        <%= f.fields_for :choices do |p| %>
            <div class="form-group">
                <%= p.label :choices %><br>
                <%= p.text_field :content,class:"form-control"%>
            </div>
            <div class="form-check">
                <%= p.check_box :is_correct %>
                <%= p.label :is_correct, "This is the answer" %>
            </div>
        <% end %>

        <div>
            <%= f.submit btn_msg, class: 'btn btn-primary btn-block'%>
        </div>
    </div>
<% end %>

app/views/admin/words/edit.html.erb
<div class="bg-image"id="bg-image_edit"></div>
<div class="bg-text">
    <div class="col-sm-6 mx-auto">
        <h1 class="text-center">Edit</h1>
        <div class="border-top p-3"></div>
        <%= render "form","btn_msg":"Edit account" %>
        <%# btn_msgには、Edit accountを表示する というコード %>
    </div>
    <%= link_to "Back",admin_category_words_path, class:"btn btn-light my-2" %>
</div>

app/views/admin/words/index.html.erb
<div class="container p-4">
    <h2 class="card-title text-center"><%= @category.title %></h2>
    <h5 class="card-title text-center"><%= @category.description %></h5>
    <%= link_to "New Word",new_admin_category_word_path(@category),class:"btn btn-secondary m-2 text-center" %>

    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Word</th>
                <th scope="col">Answer</th>
                <th scope="col">Setting</th>
            </tr>
        </thead>
        <tbody>
            <% @words.each do |word| %>
                <tr>
                    <td><%= word.content %></td>
                    <td><%= word.correct_answer.content %></td>
                    <td><%= link_to "Edit",edit_admin_category_word_path(@category,word), class:""%>/<%= link_to "Remove",admin_category_word_path(@category,word),method: :delete,data:{confirm:"Are you sure?"}%>
                    </td> 
                </tr>
            <% end %>
        </tbody>
    </table>
     <%= will_paginate %>
   
    <%= link_to "Back",admin_categories_path, class:"btn btn-light my-2" %>
</div>

app/views/admin/words/new.html.erb
<div class="bg-image"></div>

<div class="bg-text">
    <div class="col-sm-6 mx-auto">

        <h1 class="text-center">Create New word</h1>
        <div class="border-top p-3"></div>
        <%= render "form","btn_msg":"Create new word" %>

    </div>
    <%= link_to "Back",admin_category_words_path, class:"btn btn-light my-2" %>
</div>