config/routes.rb
Rails.application.routes.draw do
  get 'words/index'
  root 'static_pages#home'
  get '/signup',to:'users#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/login', to:'sessions#new'
  delete '/logout',to:'sessions#destroy'
  resources :users do
    member do
      get 'following', 'followers'
    end
  end
  resources :sessions
  resources :relationships,only:[:create,:destroy]
  namespace :admin do
    resources :static_pages do
      member do
        get 'admin_page'
      end
    end
    resources :users
    resources :categories do
      resources :words
    end
  end
  resources :categories
  get '/learned',to:'categories#learned'
  get '/not_learned',to:'categories#not_learned'
  resources :lessons do
    resources :answers
  end
  resources :words,only:[:index]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :lessons, dependent: :destroy
  before_save {email.downcase!}
  # REGEX = Regular expression
  # To validate correct email structure
  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  has_many :answers, through: :lessons
  has_many :categories, through: :lessons
  validates :name,presence:true,length:{ maximum:50 }
  validates :email,presence:true,length:{ maximum:225 },
              format:{with:EMAIL_REGEX},
              uniqueness: {case_senmsitive: false }
  has_secure_password
  validates :password,length:{ minimum:6 },allow_nil: true
  validates :name, presence: true
  validates :email, presence: true

  mount_uploader :picture,PictureUploader

  has_many :active_relationships, class_name: "Relationship",
                                foreign_key: "follower_id",
                                dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship",
                                  foreign_key: "followed_id",
                                  dependent: :destroy
  has_many :following,  through: :active_relationships, source: :followed
  has_many :followers,  through: :passive_relationships

  def follow(other_user)
  	following << other_user
  end
  def unfollow(other_user)
    active_relationships.find_by(followed: other_user).destroy
  end
  def following?(other_user)
    following.include?(other_user)
  end
  def relationship(other_user)
    active_relationships.find_by(followed_id: other_user.id)
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    @users = User.all
  end

  def update
    @user = User.find(params[:id])
    @user.update_attribute(:is_admin,true)
    redirect_to admin_users_url
  end

  def destroy
    @user = User.find(params[:id])
    @user.update_attribute(:is_admin,false)
    redirect_to admin_users_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @users = Activity.where("user_id = ?", @user.id).order(created_at: :desc).paginate(page: params[:page], per_page: 6)
  end
  
  def new
    @user = User.new
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 10)
  end
  
  def create
    @user = User.new(users_params)
    if @user.save
      redirect_to root_url
    else
      render "new"
    end
  end

  def update
    @user =User.find(params[:id])
    if @user.update(users_params)
      redirect_to current_user
    else
      render”edit”
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def following
    @user = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page], per_page: 10)
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page], per_page: 10)
  end

  private
  def users_params
    params.require(:user).permit(:name,:email,:password, :password_confirmation,:picture)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>

    <%= render "shared/error_message", object:f.object %>
    <%# エラーメッセージ %>
    <div class="form-group">
        <%# form-groupに変えている %>
        <%= f.label :Name %><br>
        <%= f.text_field :name,class:"form-control"%>
    </div>

    <div class="form-group">
        <%= f.label :email %><br>
        <%= f.email_field :email,class:"form-control" %>
        <%# 上記２つのemailは、labelをクリックしたらテキストボックスが光るというコネクションを示している %>
    </div>

    <div class="form-group">
        <%= f.label :password %><br>
        <%= f.password_field :password,class:"form-control"%>
    </div>

    <div class="form-group">
        <%= f.label :password_confirmation %><br>
        <%= f.password_field :password_confirmation,class:"form-control"%>
    </div>

    <% if logged_in? %>
        <div class="form-group">
            <%= f.label :picture %><br>
            <%= f.file_field :picture, accept: "image/jpeg, image/gif, image/png",class:"form-control"%>
        </div>
    <% end %>
   

    <%# 画像アップロード %>
    <div>
        <%= f.submit btn_msg, class: 'btn btn-primary btn-block'%>
        <%# btn_msgはただの変数なので変更可能 => renderに続く%>
    </div>
<% end %>

app/views/users/dash_board.html.erb
<div class="bg-image" id="bg-image3"></div>

<div class="bg-text mt-5" id="bg-text3">
    <div class="row">
        <div class="col-md-4">
            <h1>Dash board</h1>
            <% if current_user.picture? %>
                <%=image_tag current_user.picture.url, class:"img-size rounded-circle"%>
            <% end %>
            <h2 class="card-title text-center"><%= current_user.name %></h2>
            <div class="card-body">
                <hr>
                <div class>
                   <%= link_to "Learned words",words_path, class:"btn btn-success" %> 
                </div>
            </div>
        </div>

        <div class="col-md-8 text-center">
            <h1 m-2>All ACTIVITIES</h1>
            <div class="activity_table">
                <table class="text-left">
                    <% @static_pages.each do |activity| %>
                        <% if activity.action_type == "Relationship" %>
                            <tr>
                                <% if current_user ==  activity.user%>
                                    <td class="p-2"><%= link_to "YOU",activity.user %></td>
                                <% else %>
                                    <td class="p-2"><%= link_to activity.user.name,activity.user %></td>
                                <% end %>
                                <td>followed</td>
                                <td class="p-2"><%= link_to activity.action.followed.name, activity.action.followed %></td>
                                <td><%= time_ago_in_words(activity.created_at) %></td>
                            </tr>
                        <% else %>
                            <tr>
                                <% if current_user ==  activity.user%>
                                    <td class="p-2"><%= link_to "YOU",activity.user %></td>
                                <% else %>
                                    <td class="p-2"><%= link_to activity.user.name,activity.user %></td>
                                <% end %>
                                <td>learned</td>
                                <td class="p-2"><%= activity.action.correct_answers %> of <%= activity.action.words.count %>in
                                <%=link_to activity.action.category.title,activity.action %></td>
                                <td><%= time_ago_in_words(activity.created_at) %></td>
                            </tr> 
                        <% end %>
                    <% end %>
                </table>
                <div class="activity_table">
                    <%= will_paginate %>
                </div>
            </div>
        </div>
    </div>
        
</div>

app/views/users/edit.html.erb
<div class="bg-image"id="bg-image_edit"></div>
<div class="bg-text" id="edit_position">
    <div class="col-sm-6 mx-auto">
        <h1 class="text-center">Edit</h1>
        <div class="border-top p-3"></div>
        <%= render "form","btn_msg":"Edit account" %>
        <%# btn_msgには、Edit accountを表示する というコード %>
    </div>
</div>

app/views/users/followers.html.erb
<div class="bg-image"id="bg-image_edit"></div>
<div class="bg-text">
    <div class="col-sm-6 mx-auto">
        <h1 class="text-center">Followers</h1>
    </div>
    <div class="paginate text-center">
    </div>
    <div class="row">
        <% @users.each do |followers| %>
            <div class="col-6">
                <div class="media p-2">
                    <div class="media-body p-1">
                        <% if followers.picture? %>
                            <%=image_tag followers.picture.url, class:"img-size rounded-circle"%>
                        <% end %>
                        <%= link_to followers.name,user_path(followers), class:"h3" %>
                    </div>
                </div>
            </div>
        <% end %>
    </div>


     <div class="paginate text-center">
        <%= will_paginate %>
    </div>
</div>

app/views/users/following.html.erb
<div class="bg-image"id="bg-image_edit"></div>
<div class="bg-text">
    <div class="col-sm-6 mx-auto">
        <h1 class="text-center">following</h1>
    </div>
    <div class="paginate text-center">
    </div>
    <div class="row">
        <% @users.each do |following| %>
            <div class="col-6">
                <div class="media p-2">
                    <div class="media-body p-1">
                        <% if following.picture? %>
                            <%=image_tag following.picture.url, class:"img-size rounded-circle"%>
                        <% end %>
                        <%= link_to following.name,user_path(following), class:"h3" %>
                    </div>
                </div>
            </div>
        <% end %>
    </div>


     <div class="paginate text-center">
        <%= will_paginate %>
    </div>
</div>

app/views/users/index.html.erb
<div class="bg-image"id="bg-image_edit"></div>
<div class="bg-text">
    <div class="col-sm-6 mx-auto">
        <h1 class="text-center">Users</h1>
    </div>
    <div class="paginate text-center">
        <%= will_paginate %>
    </div>
    <div class="row">
        <% @users.each do |user| %>
            <div class="col-6">
                <div class="media p-2">
                    <div class="media-body p-1">
                        <% if user.picture? %>
                            <%=image_tag user.picture.url, class:"img-size rounded-circle"%>
                        <% end %>
                        <%= link_to user.name,user, class:"h3"%>
                    </div>
                </div>
            </div>
        <% end %>
    </div>


     <div class="paginate text-center">
        <%= will_paginate %>
    </div>
</div>

app/views/users/new.html.erb
<div class="bg-image"></div>

<div class="bg-text">
    <div class="col-sm-6 mx-auto">

        <h1 class="text-center">Sign up</h1>
        <div class="border-top p-3"></div>
        <%= render "form","btn_msg":"Create new account" %>

    </div>
</div>

app/views/users/show.html.erb
<div class="bg-image" id="bg-image3"></div>

<div class="bg-text mt-5" id="bg-text3">
    <div class="row">
        <div class="col-md-4">
            <div class="p-3 text-center">
                <% if @user.picture? %>
                    <%=image_tag @user.picture.url, class:"img-size rounded-circle"%>
                <% end %>
            </div>
            <h2 class="card-title text-center"><%= @user.name %></h2>
            <div class="card-body">
                <p class="card-text text-center"><%= @user.email %></p>
                <div class="follow_button">
                    <% if current_user != @user %>
                        <% unless current_user.following?(@user) %>
                            <%= button_to "Follow",relationships_path,params:{followed_id: @user},class:"btn btn-sm btn-success"%>
                        <% else %>
                            <%= button_to "unfollow",relationship_path(current_user.relationship(@user)),method: :delete,class:"btn btn-sm btn-secondary"%>
                        <% end %>
                    <% end %>
                </div>
                <hr>
                <div class="row">
                    <div class="d-inline-block text-center col-6">
                        <h4><%= link_to @user.active_relationships.count, following_user_path(@user) %></h4>
                        <p>follows</p>
                    </div>
                    <div class="d-inline-block text-center col-6">
                        <h4><%= link_to @user.passive_relationships.count, followers_user_path(@user) %></h4>
                        <p>followers</p>
                    </div>
                </div>
                <div>
                    <%= link_to "Admin", admin_page_admin_static_page_path(@user), class: "btn btn-info" %>
                </div>
            </div>
        </div>

        <div class="col-md-8 text-center">
            <h1 m-2>All ACTIVITIES</h1>
            <div class="activity_table text-left">
                <table>
                    <% @users.each do |activity| %>
                        <% if activity.action_type == "Relationship"%>
                            <tr> 
                                <% if current_user ==  activity.user%>
                                    <td class="p-2"><%= link_to "YOU",activity.user %></td>
                                <% else %>
                                    <td class="p-2"><%= link_to activity.user.name,activity.user %></td>
                                <% end %>
                                <td class="p-2">followed</td>
                                <td class="p-2"><%= link_to activity.action.followed.name, activity.action.followed %></td>
                                <td class="p-2"><%= time_ago_in_words(activity.created_at) %></td>
                            </tr>
                        <% else %>
                            <tr>
                                 <% if current_user ==  activity.user%>
                                    <td class="p-2"><%= link_to "YOU",activity.user %></td>
                                <% else %>
                                    <td class="p-2"><%= link_to activity.user.name,activity.user %></td>
                                <% end %>
                                <td class="p-2">learned</td>
                                <td class="p-2"><%= activity.action.correct_answers %>of<%= activity.action.words.count %>/in<%=link_to activity.action.category.title,activity.action %></%=></td>
                                <td class="p-2"><%= time_ago_in_words(activity.created_at) %></td>
                            </tr>
                        <% end %>
                    <% end %>
                </table>
                <div class="activity_table">
                    <%= will_paginate %>
                </div>
            </div>
        </div>
    </div>
</div>