config/routes.rb
Rails.application.routes.draw do
  get 'words/index'
  root 'static_pages#home'
  get '/signup',to:'users#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/login', to:'sessions#new'
  delete '/logout',to:'sessions#destroy'
  resources :users do
    member do
      get 'following', 'followers'
    end
  end
  resources :sessions
  resources :relationships,only:[:create,:destroy]
  namespace :admin do
    resources :static_pages do
      member do
        get 'admin_page'
      end
    end
    resources :users
    resources :categories do
      resources :words
    end
  end
  resources :categories
  get '/learned',to:'categories#learned'
  get '/not_learned',to:'categories#not_learned'
  resources :lessons do
    resources :answers
  end
  resources :words,only:[:index]
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :words, dependent: :destroy
  has_many :lessons, dependent: :destroy
  has_many :users, through: :lessons
  has_many :answers, through: :lessons
  validates :title, presence: true, length:{ maximum: 20 }
  validates :description, presence: true, length:{ maximum: 50 }
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  
  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(categories_params)
    if @category.save
      redirect_to admin_category_words_url(@category)
    else
      render "new"
    end
  end

  def update
    @category = Category.find(params[:id])
      if @category.update(categories_params)
        redirect_to admin_categories _url 
      else
        render "edit"
      end
  end
                                                      # updateでは、editの要領で受け取った値を、updateで更新してしまう。


  def edit
    @category = Category.find(params[:id])
                                                      # 編集するデータを探してくる
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to admin_categories_url
  end

                                                      # edit.htmlで入力されて、fに代入されて@userあてに届いた値をparamsで選別、取得。それを元にデータを検索する。
                                                      # ruting的に、自動でupdateメソッドにも飛んでいるので、editで取得した値はupdateで処理される。
  private
  def categories_params
    params.require(:category).permit(:title,:description)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.paginate(page: params[:page], per_page: 6)
  end

  def learned

  end

  def not_learned

  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/_form.html.erb
<%= form_for([:admin,@category]) do |f| %>

    <%= render "shared/error_message", object: f.object %>
    <%# エラーメッセージ %>
    <div class="form-group">
        <%# form-groupに変えている %>
        <%= f.label :title %><br>
        <%= f.text_field :title,class:"form-control"%>
    </div>
    <div class="form-group">
        <%= f.label :description %><br>
        <%= f.text_area :description,class:"form-control"%>
    </div>
    <div>
        <%= f.submit btn_msg, class: 'btn btn-primary btn-block'%>
        <%# btn_msgはただの変数なので変更可能 => renderに続く%>
    </div>
    
<% end %>

app/views/admin/categories/edit.html.erb
<div class="bg-image"id="bg-image_edit"></div>
<div class="bg-text">
    <div class="col-sm-6 mx-auto">
        <h1 class="text-center">Edit</h1>
        <div class="border-top p-3"></div>
        <%= render "form","btn_msg":"Edit account" %>
        <%# btn_msgには、Edit accountを表示する というコード %>
    </div>
</div>

app/views/admin/categories/index.html.erb
<div class="container p-4">
<p class="lead text-muted text-center">Administrater Categories</p>
    <%= link_to "Create new Category",new_admin_category_path,class:"btn btn-secondary text-center m-2" %>
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Title</th>
                <th scope="col">Description</th>
                <th scope="col">Settings</th>
            </tr>
        </thead>
        <tbody>
            <% @categories.each do |category| %>
                <tr>
                    <th scope="row"><%= link_to category.title, admin_category_words_path(category,@word), class:"btn btn-light my-2" %></th>
                    <td><%=category.description%></td>
                    <td><%= link_to "Edit",edit_admin_category_path(category), class:"" %>/<%= link_to "Remove",admin_category_path(category),method: :delete,data:{confirm:"Are you sure?"}%></td>
                </tr>
            <% end %>
        </tbody>     
    </table>
    <%= will_paginate %>
    <%= link_to "Back", admin_page_admin_static_page_path(current_user), class:"btn btn-light my-2" %>
</div>

app/views/admin/categories/new.html.erb
<div class="bg-text">
    <div class="col-sm-6 mx-auto">
        <h1 class="text-center">New Category</h1>
        <div class="border-top p-3"></div>
        <%= render "form","btn_msg":"Create new Category" %>
    </div>
</div>

app/views/admin/categories/show.html.erb
<div class="container p-4">
    <h2 class="card-title text-center"><%= @category.title %></h2>
    <h5 class="card-title text-center"><%= @category.description %></h5>
    <%= link_to "New Word",new_admin_category_word_path(@category),class:"btn btn-secondary m-2 text-center" %>

    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Word</th>
                <th scope="col">Answer</th>
                <th scope="col">Setting</th>
            </tr>
        </thead>
    </table>
    <%= link_to "Back",admin_categories_path, class:"btn btn-light my-2" %>
</div>