config/routes.rb
Rails.application.routes.draw do
  get 'words/index'
  root 'static_pages#home'
  get '/signup',to:'users#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/login', to:'sessions#new'
  delete '/logout',to:'sessions#destroy'
  resources :users do
    member do
      get 'following', 'followers'
    end
  end
  resources :sessions
  resources :relationships,only:[:create,:destroy]
  namespace :admin do
    resources :static_pages do
      member do
        get 'admin_page'
      end
    end
    resources :users
    resources :categories do
      resources :words
    end
  end
  resources :categories
  get '/learned',to:'categories#learned'
  get '/not_learned',to:'categories#not_learned'
  resources :lessons do
    resources :answers
  end
  resources :words,only:[:index]
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :words, dependent: :destroy
  has_many :lessons, dependent: :destroy
  has_many :users, through: :lessons
  has_many :answers, through: :lessons
  validates :title, presence: true, length:{ maximum: 20 }
  validates :description, presence: true, length:{ maximum: 50 }
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  
  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(categories_params)
    if @category.save
      redirect_to admin_category_words_url(@category)
    else
      render "new"
    end
  end

  def update
    @category = Category.find(params[:id])
      if @category.update(categories_params)
        redirect_to admin_categories _url 
      else
        render "edit"
      end
  end
                                                      # updateでは、editの要領で受け取った値を、updateで更新してしまう。


  def edit
    @category = Category.find(params[:id])
                                                      # 編集するデータを探してくる
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to admin_categories_url
  end

                                                      # edit.htmlで入力されて、fに代入されて@userあてに届いた値をparamsで選別、取得。それを元にデータを検索する。
                                                      # ruting的に、自動でupdateメソッドにも飛んでいるので、editで取得した値はupdateで処理される。
  private
  def categories_params
    params.require(:category).permit(:title,:description)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.paginate(page: params[:page], per_page: 6)
  end

  def learned

  end

  def not_learned

  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/index.html.erb
<div class="bg-image"id="bg-image_index"></div>
<div class="bg-text" id="bg-text_index">
    <h1 class="text-center">Lessons</h1>
    <div class="container" id="container_index">
        <div class="p-2 mx-4 text-left">
            <%= link_to "All",categories_path, class:"btn btn-secondary mx-2 px-4" %>
            <%= link_to "Learned",learned_path, class:"btn btn-secondary mx-2" %>
            <%= link_to "Not Learned",not_learned_path, class:"btn btn-secondary mx-2" %>
        </div>
        <div class="row">
            <% @categories.each do |category| %>
                <div class="card-deck mb-3 ml-1 text-center col-4 text-dark">
                    <div class="card mb-4 shadow-sm"id="card_background">
                        <div class="card-header">
                            <h2 class="my-0 font-weight-normal"><%= category.title %></h2>
                        </div>
                        <div class="card-body">
                            <ul class="list-unstyled mt-1 mb-1">
                                <%= category.description %>
                            </ul>
                                <% if category.lessons.where(user_id: current_user, category_id: category).any? %>
                                    <%= link_to "Resoult",lesson_path(id: category.id),class: 'btn btn-success' %>
                                <% else %>
                                    <%= link_to "Start Lesson",lessons_path(category_id: category.id),method: :post,class: 'btn btn-primary' %>
                                <% end %>
                        </div>
                    </div>
                </div>
            <% end %>
            <div class="paginate col-md-6 offset-md-3">
                <%= will_paginate %>
            </div>
        </div>
    </div>
</div>

app/views/categories/learned.html.erb
<div class="bg-image"id="bg-image_index"></div>
<div class="bg-text" id="bg-text_index">
    <h1 class="text-center">Learned Lessons</h1>
    <div class="container" id="container_index">
        <div class="p-2 mx-4 text-left">
            <%= link_to "All",categories_path, class:"btn btn-secondary mx-2 px-4" %>
            <%= link_to "Learned",learned_path, class:"btn btn-secondary mx-2" %>
            <%= link_to "Not Learned",not_learned_path, class:"btn btn-secondary mx-2" %>
        </div>
    </div>
</div>

app/views/categories/not_learned.html.erb
<div class="bg-image"id="bg-image_index"></div>
<div class="bg-text" id="bg-text_index">
    <h1 class="text-center">Not Learned Lessons</h1>
    <div class="container" id="container_index">
        <div class="p-2 mx-4 text-left">
            <%= link_to "All",categories_path, class:"btn btn-secondary mx-2 px-4" %>
            <%= link_to "Learned",learned_path, class:"btn btn-secondary mx-2" %>
            <%= link_to "Not Learned",not_learned_path, class:"btn btn-secondary mx-2" %>
        </div>
    </div>
</div>